apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e73x6n51q-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5777ed1812d7a58f7e86003ff7f4b6888c3af0b8@sha256:dff437ec4a096b9e69a6a2513966bea3c6ed02877ebcfe77e1c11e6ef1946e2c
          name: container-image
